
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Sobrescribir variables del Dockerfile
      - NODE_ENV=production
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=micro_user
      - DB_USER=admin
      - DB_PASSWORD=F3cTyv8FD58zyxhQISE6
    env_file:
      - .env  # Variables adicionales desde archivo
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: micro_user
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: F3cTyv8FD58zyxhQISE6
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge